from __future__ import print_function
import math
import time
def pt(par):
    print(par)
    time.sleep(2)
def skip(x):
    print(x,'(words are omitted here)')
    time.sleep(2)
pt('you open your eye')
pt('someone walking towards you')
pt('he says: are you fine')
a=input('1. Nicolascage...? 2.trach earth people 3.son!')
if a==1:
    pt('doctor')
    pt('you finally waked doctor')
    pt('(he pulls you up)')
    pt('thouse russian already lost')
    pt('fire is already on the earth and we need to hurry up')
    pt('quickly pick a strongest human')
    b=input('1.you looks like Nicolascage 2.are you Nicolascage')
    if b==1:
        pt('i am your assistant Nicolascage')
        pt('but i am not Nicolascage anymore')
        pt('because there is only 1 Nicolascage on the earth')
        pt('dont care that much')
        pt('we already sent the offers to the earth')
        pt('go interview quickly')
        pt('lets go')
    else:
        pt('i. i. i am not Nicolascage')
        pt('how i can be Nicolascage')
        pt('its a wrong guy')
        pt('your head definitely broked doctor')
        pt('les go interview')
    pt('doctor')
    pt('this is the place for the interview')
    pt('we are going to pick te strongest human in here')
    pt('to save the world')
    pt('are you ready')
    pt('...')
    pt('(Yes)')
    pt('ok')
    pt('come interviewer')
    pt('coming in')
    pt('...')
    pt('man:hello sir')
    pt('hello yongman')
    pt('what is your power')
    pt('man:my power is heart bomb')
    pt('heart bomb, interesting')
    pt('show me')
    pt('man:im ready ot do it')
    pt('(the man taking of his pants)')
    pt('dont look! doctor')
    pt('he covered up your eyes')
    pt('...')
    pt('put your pants on!')
    pt('...')
    pt('doctor')
    pt('this due is sick. so..')
    c=input('1.i like this due 2.i want him if he is a girl')
    if c==1:
        pt('(yes)')
        pt('o~')
        pt('man:thanks sir')
        pt('man:hey')
        pt('man:(thumbs up)')
        pt('man:im here')
        pt('man:lets do it')
        pt('the man left')
    else:
        pt('what?')
        skip('')
    pt('next!')
    pt('...')
    pt('man:hello')
    pt('man:this is unlucky man')
    pt('man:every where i am where became unlucky')
    pt('man:every one will becaom unlucky')
    pt('doctor, do oyu want him')
    d=input('1.sorry 2.sorry 3.sorry 4.sorry')
    pt('man:you all will became unlucky!')
    pt('man:we will see')
    pt('next')
    pt('3rd man: i am faker')
    pt('man:it means i can fake')
    pt('are you sure')
    pt('show it')
    pt('he turns around and put on a thanos mask')
    pt('(x word are omitted here)')
    pt('...')
    e=input('1.yes 2.no')
    if e==1:
        pt('you are in')
        pt('(words are omitted here)')
    else:
        pt('you are not in')
        pt('you all will be regret')
        pt('take off the mask')
        pt('(words are omitted here)')
    pt('next')
    pt('man:this is copyman')
    pt('he is repeating what you do')
    pt('(words are omitted here)')
    f=input('1.we need repeater 2.we need a pigeon')
    if f==1:
        pt('congraduation')
        pt('(words are omitted here)')
    else:
        pt('seriousely?')
        pt('(words are omitted here)')
    pt('wow')
    pt('what is your name~')
    pt('doll: this is montage')
    pt('what is your talent~')
    pt('acting cute')
    skip('')
    g=input('1.we need this kind of prople 2.this kind of people is what we need')
    pt('next')
    pt('someone dress like Mccree walk in')
    skip('')
    h=input('1.i like this feel 2.i dont like this kind')
    if h==1:
        pt('you are in')
        skip('')
    else:
        pt('you are not in')
        skip('')
    pt('next')
    pt('i am hear too the dragon')
    skip('')
    i=input('1.why not 2.we need the hear to the dragon, not dinosour')
    if i==1:
        pt('you are in')
        skip('')
    else:
        pt('why reject us?')
        skip('')
    pt('next')
    pt('this is distroyer')
    pt('i will explode if im get excited')
    skip('few')
    pt('he exploded')
    pt('(earth crashed)')
    skip('1000')
    print('Achievement: the doctor which saved the world')
elif a==2:
    pt('my name is Nicolascage')
    pt('im not a *** trash')
    pt('what trash *** **** you are')
    b=input('1.dry trash 2.wet trash 3.harmful trash 4.i am not *** *** trash')
    if b==4:
        pt('you do have some skill')
        pt('than what kinds trash lobster shell is')
        c=input('1.dry trash 2.wet trash 3.ther is no**** **** **** robster **** *** ***')
        if c==1:
            pt('******')
            pt('according to the ******** xxxxxx instruction')
            pt('all the sea/river food is wet trash')
            pt('*** *** back to the home star and learn how to do waste classification')
            pt('(slap)')
            pt('sea/river food are all under wet trash catagory')
        elif c==2:
            pt('GREAT~~')
            pt('than what kind of trash sputum is')
            d=input('1.i am here to destroy earth 2.i dont spit')
            if d==1:
                pt('I **************** destroy earth')
                pt('**********distroy earth')
                pt('(punch)')
                pt('(the distroyer next door exploded)')
                skip('')
                pt('end:what is going on???????????????')
            else:
                pt('i am not asking you do you do it or not')
                pt('i am asking what king of trash it is')
                pt('huh')
                pt('huh')
                pt('(the distroyer next door exploded)')
                skip('')
                pt('end:what is going on???????????????')
        else:
            pt('what')
            pt('there is no robster in your home?')
            pt('come on, come on, come on')
            pt('...')
            pt('...')
            pt('and you to are in a resturant having robster')
            skip('')
            pt('the end: true love')
    else:
        pt('*** *** back to the home star and learn how to do waste classification')
        pt('(slap)')
        pt('You are not domestic waste, so its not easy to classification')
else:
    pt('dad!')
    pt('why you are here')
    pt('borther is coming here soon')
    pt('we need to hurry up')
    pt('...')
    pt('...')
    pt('...')
    pt('we run out of time')
    pt('brother is delayed')
    pt('the army is also start moving')
    pt('but i think the chance we are getting it dong is so small')
    pt('im going to do this in my way')
    pt('im going to the past')
    pt('to stop the birth of brother')
    b=input('1.stop birth? 2.punch him')
    if b==1:
        pt('yea')
        pt('this is the only way left')
        pt('btu we need to find 4 treasure to go to the past')
        pt('so')
        pt('where we are going to first')
        c=input('1.the speed trail')
        skip('')
        pt('this is the speed trail')
        pt('i will put this cap under this bottle (a clear glass bottle)')
        pt('and spin 3 bottle as fas as i can (super slow)')
        pt('are you ready?')
        pt('(yes)')
        pt('ok lets go')
        print('| |     |.|     | |')
        print('| |      |.|    | |')
        print('| |       |.|  | |')
        print('| |        |.|| |')
        print('| |          | |')
        print('| |         | | |.|')
        print('| |        | |   |.|')
        print('| |     | |     |.|')
        print(' | |     | |   |.|')
        print('  | |    | |  |.|')
        print('    | |  | | |.|')
        print('       || |.|')
        print('        ||.| |')
        print('       |.||')
        print('       |.| |')
        print('     |.|| ||')
        print('   |.|  | ||')
        print('    |.||| |')
        print('     ||.| |')
        print('   | | |.|| |')
        print('  | |    |.|  | |')
        print(' | |     |.| | |')
        print(' | |     |.||') 
        print(' | |   | |.|')
        print('  | || | |.|')
        print('   || |  |.| ')
        print('  | | | ||.|') 
        print('  | |   ||.|') 
        print('  | |    |.||') 
        print('  | |   |.|  | |') 
        print('  | |  |.|    | |') 
        print('  | | |.| | |') 
        pt('skip th process')
        pt('.')
        pt('..')
        pt('...')
        pt('.')
        pt('..')
        pt('...')
        print(' | |  |.|  | |') 
        print('  | |  |.|') 
        print('      | || | |') 
        print('     |.|| | |') 
        print('      |.|| || |') 
        print('     |.|| || |') 
        print('     |.|| || |') 
        print('   |.|  | |  | |') 
        print('|.|     | |     | |')
        print(' A       B       C')
        d=input('where is it')
        if d==a:
            skip('a lot of process')
            pt('you went back to the start of the story')
        else:
            pt('you ***** blind?')
            pt('your son killed you')
    else:
        pt('you killed son')
        pt('you killed your kid')